adding mysql
bradmallett/quotes pull request #2
Opened 2018-03-20 20:00 UTC by bradmallett

2018-03-20 20:23 UTC, mmallett commented on index.view.php
> +); background-repeat: no-repeat; width: 100%; height: 100%; background-position: center; background-size: cover;">
You should only define the `background-image` here, and use your style sheets to define the height, width, position etc.

2018-03-20 20:23 UTC, mmallett commented on index.view.php
> +
needs `<!DOCTYPE html>` to declare the HTML as HTML5

2018-03-20 20:23 UTC, mmallett commented on index.view.php
> +<html>
Delete this

2018-03-20 20:23 UTC, mmallett commented on mysql.text
> +
Why does every line in this file start with +

2018-03-20 20:23 UTC, mmallett commented on index.view.php
> +    <link href="main.css" type="text/css" rel="stylesheet"/>
You need viewport metatag if you're going to make this responsive, also should include charset metatag.

I usually copy those from the bootstrap starter template https://getbootstrap.com/docs/4.0/examples/starter-template/

2018-03-20 21:00 UTC, bradmallett commented on mysql.text
> +
Yeah that's weird. they don't have it in my editor... idk

2018-03-20 21:37 UTC, bradmallett commented on index.view.php
> +<html>
I will, I just put it there as a placeholder. I want to keep <p>Yogi Berra</p> though. its the same in all pages. theyre all quotes from him

2018-03-20 23:07 UTC, mmallett commented on index.view.php
> +<html>
That's fine, I mean delete the extra `<html>` opening tag you have on line 19

2018-03-21 01:00 UTC, mmallett requested changes

2018-03-21 01:00 UTC, mmallett commented on functions.php
> +function fetchAllQuotes($pdo) {
This function name doesn't make sense. You are fetching 1 quote, not all. Maybe `fetchQuote()`

2018-03-21 01:00 UTC, mmallett commented on mysql.text
> +create table quotes (id integer PRIMARY KEY AUTO_INCREMENT, quote text NOT NULL);
Why don't you include in the table the person that said the quote?

2018-03-21 01:00 UTC, mmallett commented on quotes.class.php
> +    class Quotes {
Generally, you only put one class in each file, and the only thing in that file is the class. So you should have a photos.class.php as well.

2018-03-21 01:00 UTC, mmallett commented on main.css
> +    height: 550px;
You are forcing the body to be exactly 550px?

2018-03-21 01:00 UTC, mmallett commented on mysql.text
> +10. Congratulations. I knew the record would stand until it was broken.
These are quality quotes hahaha

2018-03-21 01:00 UTC, mmallett commented on index.php
> +
You should think about how to structure your code in folders to make it more manageable. It's fine now when you only have 1 page, but imagine you have 3, or 20, with 15 classes. This one folder will be very crowded very quickly.

I would suggest something like this, where you separate classes and views. They serve very different purposes. Classes represent your database, and views glue together information into HTML

Look at this structure
```
index.php
classes/
    photos.class.php
    quotes.class.php
views/
    quote.php  // for gathering information, any logic you need to perform for your main page
    quote.view.php // all the html that is specific to the quote, in this case that would be everything
utils/
    db.utils.php // I would put the connect to db in here, and other stuff like that

You can put the `fetchQuotes` as a static method on your quote class

2018-03-21 01:03 UTC, mmallett commented on index.view.php
> +        <p><?= $quotes; ?></p>
You said this doesn't work. My guess would be that you need `$quotes->quote`

2018-03-21 14:47 UTC, bradmallett commented on mysql.text
> +create table quotes (id integer PRIMARY KEY AUTO_INCREMENT, quote text NOT NULL);
Because they're all from the same person.. Yogi Berra

2018-03-21 14:48 UTC, bradmallett commented on main.css
> +    height: 550px;
Yeah, because if it' s 100% of height, it makes you scroll down a bit. Prob a padding or margin issue huh?

2018-03-21 14:49 UTC, bradmallett commented on mysql.text
> +10. Congratulations. I knew the record would stand until it was broken.
Yeah, Yogi Berra is a hall of famer, but he's most known for his quotes. He came up with " it aint over till it's over

2018-03-21 14:51 UTC, bradmallett commented on index.php
> +
Utils... means tools in french

2018-03-21 14:51 UTC, bradmallett commented on index.php
> +
actually it's utiles.. but close

2018-03-21 15:25 UTC, mmallett commented on mysql.text
> +create table quotes (id integer PRIMARY KEY AUTO_INCREMENT, quote text NOT NULL);
Ahhhh ok

2018-03-21 15:26 UTC, mmallett commented on main.css
> +    height: 550px;
Probably yeah

2018-03-22 04:24 UTC, mmallett approved these changes

2018-03-22 04:26 UTC, merged